version: "3"
services:
  codeserver:
    image: linuxserver/code-server:latest
    container_name: codeserver
    env_file:
      - .env.codeserver
      - .env.dbt
    volumes:
      - ./codeserver/workspace/${WORKSPACE_PROJECT}:/config/workspace
      - ./codeserver/vs-code-settings.json:/config/data/User/settings.json
      # https://docs.linuxserver.io/general/container-customization
    ports:
      - 8443:8443
    extra_hosts:
      - ${HOST_NAME}:${HOST_IP}
    restart: unless-stopped
